[package]
name = "wasm_gold_rush"
version = "0.1.0"
edition = "2021"
description = "simple game with wasm-pack"

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
wasm-bindgen = "0.2"
